Shell Script to boot xv6

diff --git a/xv6-public/cmmf b/xv6-public/cmmf
--- a/xv6-public/cmmf
+++ b/xv6-public/cmmf
@@ -11,6 +11,15 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
+# make 명령어 실행2
+make fs.img
+
+# make 명령어가 에러 코드를 반환하면 스크립트 종료2
+if [ $? -ne 0 ]; then
+  echo "make failed."
+  exit 1
+fi
+
 # 에러가 발생하지 않은 경우
 ./bootxv6.sh
 
